---
deployment:
  tasks:
    - export DEPLOYPATH=/home/carme2513679/public_html/
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH